"""
pyodbc 类型存根文件
用于 LSP 类型检查
"""

from typing import Any, Optional, List, Dict, Tuple, Union, Iterator

class Connection:
    """数据库连接"""
    def close(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def cursor(self) -> 'Cursor': ...
    def execute(self, sql: str, *parameters: Any) -> 'Cursor': ...
    def getinfo(self, type_: int) -> Any: ...
    def setdecoding(self, ctype: int, encoding: str = ...) -> None: ...
    def setencoding(self, encoding: str) -> None: ...
    @property
    def autocommit(self) -> bool: ...
    @autocommit.setter
    def autocommit(self, value: bool) -> None: ...
    @property
    def timeout(self) -> int: ...
    @timeout.setter
    def timeout(self, seconds: int) -> None: ...

class Cursor:
    """游标"""
    def execute(self, sql: str, *parameters: Any) -> 'Cursor': ...
    def executemany(self, sql: str, seq_of_parameters: List[Tuple]) -> None: ...
    def fetchone(self) -> Optional[Tuple]: ...
    def fetchall(self) -> List[Tuple]: ...
    def fetchmany(self, size: int = -1) -> List[Tuple]: ...
    def close(self) -> None: ...
    def nextset(self) -> bool: ...
    def tables(self, **kwargs: Any) -> 'Cursor': ...
    def columns(self, **kwargs: Any) -> 'Cursor': ...
    def statistics(self, **kwargs: Any) -> 'Cursor': ...
    def rowIdColumns(self, **kwargs: Any) -> 'Cursor': ...
    def rowVerColumns(self, **kwargs: Any) -> 'Cursor': ...
    def primaryKeys(self, **kwargs: Any) -> 'Cursor': ...
    def foreignKeys(self, **kwargs: Any) -> 'Cursor': ...
    def procedureColumns(self, **kwargs: Any) -> 'Cursor': ...
    def procedures(self, **kwargs: Any) -> 'Cursor': ...
    def getTypeInfo(self, **kwargs: Any) -> 'Cursor': ...
    @property
    def description(self) -> List[Tuple[str, Any, int, int, int, int, bool]]: ...
    @property
    def rowcount(self) -> int: ...
    @property
    def arraysize(self) -> int: ...
    @arraysize.setter
    def arraysize(self, size: int) -> None: ...
    @property
    def messages(self) -> List[Tuple[str, str]]: ...
    def __iter__(self) -> Iterator[Tuple]: ...
    def __next__(self) -> Tuple: ...

def connect(
    connection_string: str,
    autocommit: bool = False,
    encoding: str = 'utf-8',
    timeout: int = 0,
    readonly: bool = False,
    **kwargs: Any
) -> Connection: ...

# 常量
SQL_NULL_HANDLE: int
SQL_HANDLE_ENV: int
SQL_HANDLE_DBC: int
SQL_HANDLE_STMT: int
SQL_HANDLE_DESC: int

# 数据类型
SQL_UNKNOWN_TYPE: int
SQL_CHAR: int
SQL_VARCHAR: int
SQL_LONGVARCHAR: int
SQL_WCHAR: int
SQL_WVARCHAR: int
SQL_WLONGVARCHAR: int
SQL_DECIMAL: int
SQL_NUMERIC: int
SQL_SMALLINT: int
SQL_INTEGER: int
SQL_REAL: int
SQL_FLOAT: int
SQL_DOUBLE: int
SQL_BIT: int
SQL_TINYINT: int
SQL_BIGINT: int
SQL_BINARY: int
SQL_VARBINARY: int
SQL_LONGVARBINARY: int
SQL_TYPE_DATE: int
SQL_TYPE_TIME: int
SQL_TYPE_TIMESTAMP: int
SQL_SS_TIME2: int
SQL_SS_XML: int
SQL_INTERVAL_MONTH: int
SQL_INTERVAL_YEAR: int
SQL_INTERVAL_YEAR_TO_MONTH: int
SQL_INTERVAL_DAY: int
SQL_INTERVAL_HOUR: int
SQL_INTERVAL_MINUTE: int
SQL_INTERVAL_SECOND: int
SQL_INTERVAL_DAY_TO_HOUR: int
SQL_INTERVAL_DAY_TO_MINUTE: int
SQL_INTERVAL_DAY_TO_SECOND: int
SQL_INTERVAL_HOUR_TO_MINUTE: int
SQL_INTERVAL_HOUR_TO_SECOND: int
SQL_INTERVAL_MINUTE_TO_SECOND: int

# 错误处理
class Error(Exception): ...
class Warning(Exception): ...
class InterfaceError(Error): ...
class DatabaseError(Error): ...
class DataError(DatabaseError): ...
class OperationalError(DatabaseError): ...
class IntegrityError(DatabaseError): ...
class InternalError(DatabaseError): ...
class ProgrammingError(DatabaseError): ...
class NotSupportedError(DatabaseError): ...

# 版本
version: str
