"""
PySide2 类型存根文件
用于 LSP 类型检查和代码补全

注意：这是简化的存根文件，仅包含项目中使用的主要类和方法
"""

from typing import Any, List, Optional, Callable, Union, Dict, Tuple

# QtCore
class Qt:
    """Qt 命名空间"""
    AlignCenter: int
    AlignLeft: int
    AlignRight: int
    AlignTop: int
    AlignBottom: int
    Horizontal: int
    Vertical: int
    ScrollBarAlwaysOff: int
    ScrollBarAlwaysOn: int
    ScrollBarAsNeeded: int
    WindowCloseButtonHint: int
    FramelessWindowHint: int
    WindowStaysOnTopHint: int
    WA_TranslucentBackground: int
    ApplicationModal: int
    Key_Escape: int
    Key_Return: int
    Key_Enter: int
    Key_Space: int
    LeftButton: int
    RightButton: int
    NoPen: int
    SolidPattern: int
    SmoothTransformation: int
    KeepAspectRatio: int
    IgnoreAspectRatio: int
    ElideLeft: int
    ElideRight: int
    ElideMiddle: int
    ElideNone: int
    UserRole: int
    DisplayRole: int
    EditRole: int
    TextAlignmentRole: int
    DecorationRole: int
    ToolTipRole: int
    StatusTipRole: int
    WhatsThisRole: int
    SizeHintRole: int
    FontRole: int
    BackgroundRole: int
    ForegroundRole: int
    CheckStateRole: int
    InitialSortOrderRole: int
    UserRole: int
    Checked: int
    Unchecked: int
    PartiallyChecked: int
    MatchStartsWith: int
    MatchContains: int
    MatchEndsWith: int
    MatchWildcard: int
    MatchRegExp: int
    MatchFixedString: int
    MatchCaseSensitive: int
    MatchWrap: int
    MatchRecursive: int
    ShiftModifier: int
    ControlModifier: int
    AltModifier: int
    MetaModifier: int
    KeypadModifier: int
    GroupSwitchModifier: int

class QObject:
    """Qt 对象基类"""
    def __init__(self, parent: Optional['QObject'] = None) -> None: ...
    def objectName(self) -> str: ...
    def setObjectName(self, name: str) -> None: ...
    def parent(self) -> Optional['QObject']: ...
    def children(self) -> List['QObject']: ...
    def deleteLater(self) -> None: ...
    def blockSignals(self, block: bool) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def findChild(self, type: type, name: str = ...) -> Optional[Any]: ...
    def findChildren(self, type: type, name: str = ...) -> List[Any]: ...

class QEvent:
    """事件基类"""
    def __init__(self, type: int) -> None: ...
    def type(self) -> int: ...
    def accept(self) -> None: ...
    def ignore(self) -> None: ...
    def isAccepted(self) -> bool: ...
    def setAccepted(self, accepted: bool) -> None: ...
    def spontaneous(self) -> bool: ...

class QCoreApplication(QObject):
    """核心应用程序类"""
    @staticmethod
    def instance() -> Optional['QCoreApplication']: ...
    @staticmethod
    def applicationDirPath() -> str: ...
    @staticmethod
    def applicationFilePath() -> str: ...
    @staticmethod
    def applicationName() -> str: ...
    @staticmethod
    def setApplicationName(name: str) -> None: ...
    @staticmethod
    def organizationName() -> str: ...
    @staticmethod
    def setOrganizationName(name: str) -> None: ...
    @staticmethod
    def quit() -> None: ...
    @staticmethod
    def exit(returnCode: int = 0) -> None: ...
    @staticmethod
    def processEvents(flags: int = ...) -> None: ...
    @staticmethod
    def sendEvent(receiver: QObject, event: QEvent) -> bool: ...
    @staticmethod
    def postEvent(receiver: QObject, event: QEvent, priority: int = ...) -> None: ...

class QThread(QObject):
    """线程类"""
    def __init__(self, parent: Optional[QObject] = None) -> None: ...
    def start(self, priority: int = ...) -> None: ...
    def terminate(self) -> None: ...
    def wait(self, time: int = ...) -> bool: ...
    def isRunning(self) -> bool: ...
    def isFinished(self) -> bool: ...
    @staticmethod
    def currentThread() -> 'QThread': ...
    @staticmethod
    def msleep(msecs: int) -> None: ...
    @staticmethod
    def sleep(secs: int) -> None: ...
    @staticmethod
    def usleep(usecs: int) -> None: ...

class QTimer(QObject):
    """定时器类"""
    def __init__(self, parent: Optional[QObject] = None) -> None: ...
    def start(self, msec: int) -> None: ...
    def stop(self) -> None: ...
    def isActive(self) -> bool: ...
    def setInterval(self, msec: int) -> None: ...
    def interval(self) -> int: ...
    def setSingleShot(self, singleShot: bool) -> None: ...
    def isSingleShot(self) -> bool: ...
    def timerId(self) -> int: ...
    @staticmethod
    def singleShot(msec: int, receiver: QObject, member: bytes) -> None: ...

class QRect:
    """矩形类"""
    def __init__(self, x: int = 0, y: int = 0, width: int = 0, height: int = 0) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def setX(self, x: int) -> None: ...
    def setY(self, y: int) -> None: ...
    def setWidth(self, w: int) -> None: ...
    def setHeight(self, h: int) -> None: ...
    def isEmpty(self) -> bool: ...
    def isValid(self) -> bool: ...
    def contains(self, x: int, y: int) -> bool: ...
    def contains(self, point: 'QPoint') -> bool: ...
    def intersects(self, r: 'QRect') -> bool: ...
    def intersected(self, r: 'QRect') -> 'QRect': ...
    def united(self, r: 'QRect') -> 'QRect': ...
    def topLeft(self) -> 'QPoint': ...
    def topRight(self) -> 'QPoint': ...
    def bottomLeft(self) -> 'QPoint': ...
    def bottomRight(self) -> 'QPoint': ...
    def center(self) -> 'QPoint': ...
    def moveTo(self, x: int, y: int) -> None: ...
    def moveTo(self, p: 'QPoint') -> None: ...
    def moveCenter(self, p: 'QPoint') -> None: ...
    def moveLeft(self, x: int) -> None: ...
    def moveRight(self, x: int) -> None: ...
    def moveTop(self, y: int) -> None: ...
    def moveBottom(self, y: int) -> None: ...
    def adjusted(self, dx1: int, dy1: int, dx2: int, dy2: int) -> 'QRect': ...

class QPoint:
    """点类"""
    def __init__(self, x: int = 0, y: int = 0) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def setX(self, x: int) -> None: ...
    def setY(self, y: int) -> None: ...
    def isNull(self) -> bool: ...
    def __add__(self, p: 'QPoint') -> 'QPoint': ...
    def __sub__(self, p: 'QPoint') -> 'QPoint': ...

class QSize:
    """尺寸类"""
    def __init__(self, w: int = 0, h: int = 0) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def setWidth(self, w: int) -> None: ...
    def setHeight(self, h: int) -> None: ...
    def isEmpty(self) -> bool: ...
    def isValid(self) -> bool: ...
    def isNull(self) -> bool: ...
    def expandedTo(self, other: 'QSize') -> 'QSize': ...
    def boundedTo(self, other: 'QSize') -> 'QSize': ...
    def __add__(self, s: 'QSize') -> 'QSize': ...
    def __sub__(self, s: 'QSize') -> 'QSize': ...

class QModelIndex:
    """模型索引类"""
    def __init__(self) -> None: ...
    def row(self) -> int: ...
    def column(self) -> int: ...
    def isValid(self) -> bool: ...
    def data(self, role: int = ...) -> Any: ...
    def sibling(self, row: int, column: int) -> 'QModelIndex': ...
    def child(self, row: int, column: int) -> 'QModelIndex': ...
    def parent(self) -> 'QModelIndex': ...

class QAbstractItemModel(QObject):
    """抽象项模型基类"""
    def rowCount(self, parent: QModelIndex = ...) -> int: ...
    def columnCount(self, parent: QModelIndex = ...) -> int: ...
    def data(self, index: QModelIndex, role: int = ...) -> Any: ...
    def setData(self, index: QModelIndex, value: Any, role: int = ...) -> bool: ...
    def headerData(self, section: int, orientation: Qt.Orientation, role: int = ...) -> Any: ...
    def setHeaderData(self, section: int, orientation: Qt.Orientation, value: Any, role: int = ...) -> bool: ...
    def flags(self, index: QModelIndex) -> Qt.ItemFlags: ...
    def index(self, row: int, column: int, parent: QModelIndex = ...) -> QModelIndex: ...
    def parent(self, index: QModelIndex) -> QModelIndex: ...
    def hasChildren(self, parent: QModelIndex = ...) -> bool: ...
    def insertRows(self, row: int, count: int, parent: QModelIndex = ...) -> bool: ...
    def removeRows(self, row: int, count: int, parent: QModelIndex = ...) -> bool: ...
    def insertColumns(self, column: int, count: int, parent: QModelIndex = ...) -> bool: ...
    def removeColumns(self, column: int, count: int, parent: QModelIndex = ...) -> bool: ...
    def dataChanged(self, topLeft: QModelIndex, bottomRight: QModelIndex, roles: List[int] = ...) -> None: ...
    def layoutChanged(self) -> None: ...
    def modelReset(self) -> None: ...
    def resetInternalData(self) -> None: ...
    def beginResetModel(self) -> None: ...
    def endResetModel(self) -> None: ...
    def beginInsertRows(self, parent: QModelIndex, first: int, last: int) -> None: ...
    def endInsertRows(self) -> None: ...
    def beginRemoveRows(self, parent: QModelIndex, first: int, last: int) -> None: ...
    def endRemoveRows(self) -> None: ...
    def beginInsertColumns(self, parent: QModelIndex, first: int, last: int) -> None: ...
    def endInsertColumns(self) -> None: ...
    def beginRemoveColumns(self, parent: QModelIndex, first: int, last: int) -> None: ...
    def endRemoveColumns(self) -> None: ...

class Signal:
    """信号类"""
    def connect(self, slot: Callable[..., Any], type: type = ...) -> None: ...
    def disconnect(self, slot: Callable[..., Any] = None) -> None: ...
    def emit(self, *args: Any) -> None: ...

class Slot:
    """槽装饰器"""
    def __init__(self, *types: type) -> None: ...
    def __call__(self, func: Callable[..., Any]) -> Callable[..., Any]: ...
