"""
PySide2 QtGui 类型存根文件
用于 LSP 类型检查和代码补全
"""

from typing import Any, List, Optional, Callable, Union, Dict, Tuple
from PySide2.QtCore import Qt, QObject, QEvent, Signal, QRect, QPoint, QSize

class QIcon:
    """图标类"""
    def __init__(self) -> None: ...
    def __init__(self, fileName: str) -> None: ...
    def __init__(self, other: 'QIcon') -> None: ...
    def addFile(self, fileName: str, size: QSize = ..., mode: 'QIcon.Mode' = ..., state: 'QIcon.State' = ...) -> None: ...
    def addPixmap(self, pixmap: 'QPixmap', mode: 'QIcon.Mode' = ..., state: 'QIcon.State' = ...) -> None: ...
    def pixmap(self, size: QSize, mode: 'QIcon.Mode' = ..., state: 'QIcon.State' = ...) -> 'QPixmap': ...
    def pixmap(self, w: int, h: int, mode: 'QIcon.Mode' = ..., state: 'QIcon.State' = ...) -> 'QPixmap': ...
    def actualSize(self, size: QSize, mode: 'QIcon.Mode' = ..., state: 'QIcon.State' = ...) -> QSize: ...
    def isNull(self) -> bool: ...
    def isMask(self) -> bool: ...
    def setIsMask(self, isMask: bool) -> None: ...
    def cacheKey(self) -> int: ...
    def swap(self, other: 'QIcon') -> None: ...
    @staticmethod
    def fromTheme(name: str, fallback: 'QIcon' = ...) -> 'QIcon': ...
    @staticmethod
    def hasThemeIcon(name: str) -> bool: ...
    @staticmethod
    def setThemeName(path: str) -> None: ...
    @staticmethod
    def themeName() -> str: ...
    @staticmethod
    def setThemeSearchPaths(searchpaths: List[str]) -> None: ...
    @staticmethod
    def themeSearchPaths() -> List[str]: ...

class QPixmap:
    """像素图类"""
    def __init__(self) -> None: ...
    def __init__(self, width: int, height: int) -> None: ...
    def __init__(self, size: QSize) -> None: ...
    def __init__(self, fileName: str, format: str = ..., flags: Qt.ImageConversionFlags = ...) -> None: ...
    def __init__(self, other: 'QPixmap') -> None: ...
    def isNull(self) -> bool: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def size(self) -> QSize: ...
    def rect(self) -> QRect: ...
    def depth(self) -> int: ...
    def fill(self, color: 'QColor' = ...) -> None: ...
    def mask(self) -> 'QBitmap': ...
    def setMask(self, mask: 'QBitmap') -> None: ...
    def isQBitmap(self) -> bool: ...
    def swap(self, other: 'QPixmap') -> None: ...
    def copy(self, x: int, y: int, width: int, height: int) -> 'QPixmap': ...
    def copy(self, rect: QRect = ...) -> 'QPixmap': ...
    def scaled(self, width: int, height: int, aspectMode: Qt.AspectRatioMode = ..., mode: Qt.TransformationMode = ...) -> 'QPixmap': ...
    def scaled(self, size: QSize, aspectMode: Qt.AspectRatioMode = ..., mode: Qt.TransformationMode = ...) -> 'QPixmap': ...
    def scaledToWidth(self, width: int, mode: Qt.TransformationMode = ...) -> 'QPixmap': ...
    def scaledToHeight(self, height: int, mode: Qt.TransformationMode = ...) -> 'QPixmap': ...
    def transformed(self, matrix: 'QTransform', mode: Qt.TransformationMode = ...) -> 'QPixmap': ...
    def devicePixelRatio(self) -> float: ...
    def setDevicePixelRatio(self, scaleFactor: float) -> None: ...
    def hasAlpha(self) -> bool: ...
    def hasAlphaChannel(self) -> bool: ...
    def toImage(self) -> 'QImage': ...
    @staticmethod
    def fromImage(image: 'QImage', flags: Qt.ImageConversionFlags = ...) -> 'QPixmap': ...
    @staticmethod
    def fromImageReader(reader: 'QImageReader', flags: Qt.ImageConversionFlags = ...) -> 'QPixmap': ...
    def load(self, fileName: str, format: str = ..., flags: Qt.ImageConversionFlags = ...) -> bool: ...
    def loadFromData(self, data: bytes, format: str = ..., flags: Qt.ImageConversionFlags = ...) -> bool: ...
    def save(self, fileName: str, format: str = ..., quality: int = -1) -> bool: ...
    def cacheKey(self) -> int: ...

class QBitmap:
    """位图类"""
    pass

class QImage:
    """图像类"""
    def __init__(self) -> None: ...
    def __init__(self, width: int, height: int, format: 'QImage.Format') -> None: ...
    def __init__(self, size: QSize, format: 'QImage.Format') -> None: ...
    def __init__(self, fileName: str, format: str = ...) -> None: ...
    def isNull(self) -> bool: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def size(self) -> QSize: ...
    def rect(self) -> QRect: ...
    def depth(self) -> int: ...
    def format(self) -> 'QImage.Format': ...
    def bits(self) -> bytes: ...
    def byteCount(self) -> int: ...
    def bytesPerLine(self) -> int: ...
    def fill(self, color: 'QColor') -> None: ...
    def fill(self, pixel: int) -> None: ...
    def fill(self, color: Qt.GlobalColor) -> None: ...
    def pixel(self, x: int, y: int) -> int: ...
    def pixel(self, pt: QPoint) -> int: ...
    def setPixel(self, x: int, y: int, index_or_rgb: int) -> None: ...
    def setPixel(self, pt: QPoint, index_or_rgb: int) -> None: ...
    def pixelColor(self, x: int, y: int) -> 'QColor': ...
    def pixelColor(self, pt: QPoint) -> 'QColor': ...
    def setPixelColor(self, x: int, y: int, color: 'QColor') -> None: ...
    def setPixelColor(self, pt: QPoint, color: 'QColor') -> None: ...
    def valid(self, x: int, y: int) -> bool: ...
    def valid(self, pt: QPoint) -> bool: ...
    def copy(self, x: int = 0, y: int = 0, width: int = -1, height: int = -1) -> 'QImage': ...
    def copy(self, rect: QRect = ...) -> 'QImage': ...
    def scaled(self, width: int, height: int, aspectMode: Qt.AspectRatioMode = ..., mode: Qt.TransformationMode = ...) -> 'QImage': ...
    def scaled(self, size: QSize, aspectMode: Qt.AspectRatioMode = ..., mode: Qt.TransformationMode = ...) -> 'QImage': ...
    def scaledToWidth(self, width: int, mode: Qt.TransformationMode = ...) -> 'QImage': ...
    def scaledToHeight(self, height: int, mode: Qt.TransformationMode = ...) -> 'QImage': ...
    def transformed(self, matrix: 'QTransform', mode: Qt.TransformationMode = ...) -> 'QImage': ...
    def mirrored(self, horizontally: bool = False, vertically: bool = True) -> 'QImage': ...
    def rgbSwapped(self) -> 'QImage': ...
    def invertPixels(self, mode: 'QImage.InvertMode' = ...) -> None: ...
    def colorTable(self) -> List[int]: ...
    def setColorTable(self, colors: List[int]) -> None: ...
    def colorCount(self) -> int: ...
    def setColorCount(self, colorCount: int) -> None: ...
    def allGray(self) -> bool: ...
    def isGrayscale(self) -> bool: ...
    def hasAlphaChannel(self) -> bool: ...
    def setAlphaChannel(self, alphaChannel: 'QImage') -> None: ...
    def alphaChannel(self) -> 'QImage': ...
    def hasAlphaBuffer(self) -> bool: ...
    def setAlphaBuffer(self, enable: bool) -> None: ...
    def createAlphaMask(self, flags: Qt.ImageConversionFlags = ...) -> 'QImage': ...n    def createHeuristicMask(self, clipTreshold: int = 32) -> 'QImage': ...
    def createMaskFromColor(self, color: int, mode: Qt.MaskMode = ...) -> 'QImage': ...
    def load(self, fileName: str, format: str = ...) -> bool: ...
    def loadFromData(self, data: bytes, format: str = ...) -> bool: ...
    def save(self, fileName: str, format: str = ..., quality: int = -1) -> bool: ...
    def toPixelFormat(self) -> 'QPixelFormat': ...
    @staticmethod
    def toImageFormat(pixelFormat: 'QPixelFormat') -> 'QImage.Format': ...
    @staticmethod
    def fromData(data: bytes, format: str = ...) -> 'QImage': ...
    def cacheKey(self) -> int: ...
    def dotsPerMeterX(self) -> int: ...
    def dotsPerMeterY(self) -> int: ...
    def setDotsPerMeterX(self, x: int) -> None: ...
    def setDotsPerMeterY(self, y: int) -> None: ...
    def offset(self) -> QPoint: ...
    def setOffset(self, offset: QPoint) -> None: ...
    def text(self, key: str = ...) -> str: ...
    def textKeys(self) -> List[str]: ...
    def setText(self, key: str, value: str) -> None: ...
    def devicePixelRatio(self) -> float: ...
    def setDevicePixelRatio(self, scaleFactor: float) -> None: ...

class QColor:
    """颜色类"""
    def __init__(self) -> None: ...
    def __init__(self, color: Qt.GlobalColor) -> None: ...
    def __init__(self, r: int, g: int, b: int, a: int = 255) -> None: ...
    def __init__(self, rgb: int) -> None: ...
    def __init__(self, name: str) -> None: ...
    def __init__(self, other: 'QColor') -> None: ...
    def isValid(self) -> bool: ...
    def name(self) -> str: ...
    def setNamedColor(self, name: str) -> None: ...
    def red(self) -> int: ...
    def green(self) -> int: ...
    def blue(self) -> int: ...
    def alpha(self) -> int: ...
    def setRed(self, red: int) -> None: ...
    def setGreen(self, green: int) -> None: ...
    def setBlue(self, blue: int) -> None: ...
    def setAlpha(self, alpha: int) -> None: ...
    def redF(self) -> float: ...
    def greenF(self) -> float: ...
    def blueF(self) -> float: ...
    def alphaF(self) -> float: ...
    def setRedF(self, red: float) -> None: ...
    def setGreenF(self, green: float) -> None: ...
    def setBlueF(self, blue: float) -> None: ...
    def setAlphaF(self, alpha: float) -> None: ...
    def hsvHue(self) -> int: ...
    def hsvSaturation(self) -> int: ...
    def value(self) -> int: ...
    def hsvHueF(self) -> float: ...
    def hsvSaturationF(self) -> float: ...
    def valueF(self) -> float: ...
    def hslHue(self) -> int: ...
    def hslSaturation(self) -> int: ...
    def lightness(self) -> int: ...
    def hslHueF(self) -> float: ...
    def hslSaturationF(self) -> float: ...
    def lightnessF(self) -> float: ...
    def cyan(self) -> int: ...
    def magenta(self) -> int: ...
    def yellow(self) -> int: ...
    def black(self) -> int: ...
    def cyanF(self) -> float: ...
    def magentaF(self) -> float: ...
    def yellowF(self) -> float: ...
    def blackF(self) -> float: ...
    def rgb(self) -> int: ...
    def rgba(self) -> int: ...
    def setRgb(self, r: int, g: int, b: int, a: int = 255) -> None: ...
    def setRgba(self, rgba: int) -> None: ...
    def getRgb(self) -> Tuple[int, int, int, int]: ...
    def getRgbF(self) -> Tuple[float, float, float, float]: ...
    def getHsv(self) -> Tuple[int, int, int, int]: ...
    def getHsvF(self) -> Tuple[float, float, float, float]: ...
    def getHsl(self) -> Tuple[int, int, int, int]: ...
    def getHslF(self) -> Tuple[float, float, float, float]: ...
    def getCmyk(self) -> Tuple[int, int, int, int, int]: ...
    def getCmykF(self) -> Tuple[float, float, float, float, float]: ...
    def setHsv(self, h: int, s: int, v: int, a: int = 255) -> None: ...
    def setHsvF(self, h: float, s: float, v: float, a: float = 1.0) -> None: ...
    def setHsl(self, h: int, s: int, l: int, a: int = 255) -> None: ...
    def setHslF(self, h: float, s: float, l: float, a: float = 1.0) -> None: ...
    def setCmyk(self, c: int, m: int, y: int, k: int, a: int = 255) -> None: ...
    def setCmykF(self, c: float, m: float, y: float, k: float, a: float = 1.0) -> None: ...
    def lighter(self, factor: int = 150) -> 'QColor': ...
    def darker(self, factor: int = 200) -> 'QColor': ...
    def toRgb(self) -> 'QColor': ...
    def toHsv(self) -> 'QColor': ...
    def toHsl(self) -> 'QColor': ...
    def toCmyk(self) -> 'QColor': ...
    @staticmethod
    def colorNames() -> List[str]: ...
    @staticmethod
    def fromRgb(rgb: int) -> 'QColor': ...
    @staticmethod
    def fromRgba(rgba: int) -> 'QColor': ...
    @staticmethod
    def fromRgbF(r: float, g: float, b: float, a: float = 1.0) -> 'QColor': ...
    @staticmethod
    def fromHsv(h: int, s: int, v: int, a: int = 255) -> 'QColor': ...
    @staticmethod
    def fromHsvF(h: float, s: float, v: float, a: float = 1.0) -> 'QColor': ...
    @staticmethod
    def fromHsl(h: int, s: int, l: int, a: int = 255) -> 'QColor': ...
    @staticmethod
    def fromHslF(h: float, s: float, l: float, a: float = 1.0) -> 'QColor': ...
    @staticmethod
    def fromCmyk(c: int, m: int, y: int, k: int, a: int = 255) -> 'QColor': ...
    @staticmethod
    def fromCmykF(c: float, m: float, y: float, k: float, a: float = 1.0) -> 'QColor': ...

class QFont:
    """字体类"""
    def __init__(self) -> None: ...
    def __init__(self, family: str, pointSize: int = -1, weight: int = -1, italic: bool = False) -> None: ...
    def __init__(self, other: 'QFont') -> None: ...
    def family(self) -> str: ...
    def setFamily(self, family: str) -> None: ...
    def pointSize(self) -> int: ...
    def setPointSize(self, pointSize: int) -> None: ...
    def pointSizeF(self) -> float: ...
    def setPointSizeF(self, pointSize: float) -> None: ...
    def pixelSize(self) -> int: ...
    def setPixelSize(self, pixelSize: int) -> None: ...
    def weight(self) -> int: ...
    def setWeight(self, weight: int) -> None: ...
    def bold(self) -> bool: ...
    def setBold(self, enable: bool) -> None: ...
    def italic(self) -> bool: ...
    def setItalic(self, enable: bool) -> None: ...
    def underline(self) -> bool: ...
    def setUnderline(self, enable: bool) -> None: ...
    def overline(self) -> bool: ...
    def setOverline(self, enable: bool) -> None: ...
    def strikeOut(self) -> bool: ...
    def setStrikeOut(self, enable: bool) -> None: ...
    def fixedPitch(self) -> bool: ...
    def setFixedPitch(self, enable: bool) -> None: ...
    def kerning(self) -> bool: ...
    def setKerning(self, enable: bool) -> None: ...
    def styleHint(self) -> 'QFont.StyleHint': ...
    def setStyleHint(self, hint: 'QFont.StyleHint', strategy: 'QFont.StyleStrategy' = ...) -> None: ...
    def styleStrategy(self) -> 'QFont.StyleStrategy': ...
    def setStyleStrategy(self, s: 'QFont.StyleStrategy') -> None: ...
    def style(self) -> 'QFont.Style': ...
    def setStyle(self, style: 'QFont.Style') -> None: ...
    def exactMatch(self) -> bool: ...
    def toString(self) -> str: ...
    def fromString(self, description: str) -> bool: ...
    def key(self) -> str: ...
    def cacheKey(self) -> int: ...
    def defaultFamily(self) -> str: ...
    def legacyWeight(self) -> int: ...
    def resolve(self, other: 'QFont') -> 'QFont': ...
    def swap(self, other: 'QFont') -> None: ...
    @staticmethod
    def styleHintName(styleHint: 'QFont.StyleHint') -> str: ...
    @staticmethod
    def insertSubstitution(familyName: str, substituteName: str) -> None: ...
    @staticmethod
    def insertSubstitutions(familyName: str, substituteNames: List[str]) -> None: ...
    @staticmethod
    def removeSubstitutions(familyName: str) -> None: ...
    @staticmethod
    def substitutions(familyName: str) -> List[str]: ...
    @staticmethod
    def initialize() -> None: ...
    @staticmethod
    def cleanup() -> None: ...

class QCursor:
    """光标类"""
    def __init__(self) -> None: ...
    def __init__(self, shape: Qt.CursorShape) -> None: ...
    def __init__(self, pixmap: QPixmap, hotX: int = -1, hotY: int = -1) -> None: ...
    def __init__(self, other: 'QCursor') -> None: ...
    def shape(self) -> Qt.CursorShape: ...
    def setShape(self, newShape: Qt.CursorShape) -> None: ...
    def pixmap(self) -> QPixmap: ...
    def hotSpot(self) -> QPoint: ...
    def swap(self, other: 'QCursor') -> None: ...
    @staticmethod
    def pos() -> QPoint: ...
    @staticmethod
    def pos(screen: 'QScreen') -> QPoint: ...
    @staticmethod
    def setPos(x: int, y: int) -> None: ...
    @staticmethod
    def setPos(screen: 'QScreen', x: int, y: int) -> None: ...
    @staticmethod
    def setPos(p: QPoint) -> None: ...
    @staticmethod
    def setPos(screen: 'QScreen', p: QPoint) -> None: ...

class QTransform:
    """变换类"""
    pass

class QPainter:
    """画家类"""
    pass

class QPaintEvent(QEvent):
    """绘制事件"""
    def __init__(self, paintRegion: 'QRegion') -> None: ...
    def __init__(self, paintRect: QRect) -> None: ...
    def rect(self) -> QRect: ...
    def region(self) -> 'QRegion': ...

class QResizeEvent(QEvent):
    """尺寸改变事件"""
    def __init__(self, size: QSize, oldSize: QSize) -> None: ...
    def size(self) -> QSize: ...
    def oldSize(self) -> QSize: ...

class QMoveEvent(QEvent):
    """移动事件"""
    def __init__(self, pos: QPoint, oldPos: QPoint) -> None: ...
    def pos(self) -> QPoint: ...
    def oldPos(self) -> QPoint: ...

class QCloseEvent(QEvent):
    """关闭事件"""
    pass

class QShowEvent(QEvent):
    """显示事件"""
    pass

class QHideEvent(QEvent):
    """隐藏事件"""
    pass

class QFocusEvent(QEvent):
    """焦点事件"""
    def __init__(self, type: QEvent.Type, reason: Qt.FocusReason = ...) -> None: ...
    def gotFocus(self) -> bool: ...
    def lostFocus(self) -> bool: ...
    def reason(self) -> Qt.FocusReason: ...

class QKeyEvent(QEvent):
    """键盘事件"""
    def __init__(self, type: QEvent.Type, key: int, modifiers: Qt.KeyboardModifiers, text: str = ..., autorep: bool = False, count: int = 1) -> None: ...
    def key(self) -> int: ...
    def modifiers(self) -> Qt.KeyboardModifiers: ...
    def text(self) -> str: ...
    def isAutoRepeat(self) -> bool: ...
    def count(self) -> int: ...
    def nativeScanCode(self) -> int: ...
    def nativeVirtualKey(self) -> int: ...
    def nativeModifiers(self) -> int: ...
    @staticmethod
    def matches(key: 'QKeySequence.StandardKey') -> bool: ...

class QMouseEvent(QEvent):
    """鼠标事件"""
    def __init__(self, type: QEvent.Type, localPos: 'QPointF', button: Qt.MouseButton, buttons: Qt.MouseButtons, modifiers: Qt.KeyboardModifiers) -> None: ...
    def __init__(self, type: QEvent.Type, localPos: 'QPointF', windowPos: 'QPointF', button: Qt.MouseButton, buttons: Qt.MouseButtons, modifiers: Qt.KeyboardModifiers) -> None: ...
    def __init__(self, type: QEvent.Type, localPos: 'QPointF', windowPos: 'QPointF', screenPos: 'QPointF', button: Qt.MouseButton, buttons: Qt.MouseButtons, modifiers: Qt.KeyboardModifiers) -> None: ...
    def pos(self) -> QPoint: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def globalPos(self) -> QPoint: ...
    def globalX(self) -> int: ...
    def globalY(self) -> int: ...
    def button(self) -> Qt.MouseButton: ...
    def buttons(self) -> Qt.MouseButtons: ...
    def modifiers(self) -> Qt.KeyboardModifiers: ...
    def source(self) -> Qt.MouseEventSource: ...
    def flags(self) -> Qt.MouseEventFlags: ...

class QWheelEvent(QEvent):
    """滚轮事件"""
    pass

class QDragEnterEvent(QEvent):
    """拖入事件"""
    pass

class QDragMoveEvent(QEvent):
    """拖动移动事件"""
    pass

class QDragLeaveEvent(QEvent):
    """拖离事件"""
    pass

class QDropEvent(QEvent):
    """放置事件"""
    pass
