"""
PySide2 QtWidgets 类型存根文件
用于 LSP 类型检查和代码补全
"""

from typing import Any, List, Optional, Callable, Union, Dict, Tuple, overload
from PySide2.QtCore import Qt, QObject, QEvent, Signal, QRect, QPoint, QSize, QModelIndex, QAbstractItemModel

class QWidget(QObject):
    """控件基类"""
    def __init__(self, parent: Optional['QWidget'] = None, flags: Qt.WindowFlags = ...) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def close(self) -> bool: ...
    def isVisible(self) -> bool: ...
    def isEnabled(self) -> bool: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def isWindow(self) -> bool: ...
    def window(self) -> Optional['QWidget']: ...
    def parentWidget(self) -> Optional['QWidget']: ...
    def setParent(self, parent: Optional['QWidget']) -> None: ...
    def geometry(self) -> QRect: ...
    def setGeometry(self, x: int, y: int, w: int, h: int) -> None: ...
    def setGeometry(self, rect: QRect) -> None: ...
    def pos(self) -> QPoint: ...
    def size(self) -> QSize: ...
    def rect(self) -> QRect: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def move(self, x: int, y: int) -> None: ...
    def move(self, p: QPoint) -> None: ...
    def resize(self, w: int, h: int) -> None: ...
    def resize(self, s: QSize) -> None: ...
    def minimumSize(self) -> QSize: ...
    def setMinimumSize(self, w: int, h: int) -> None: ...
    def setMinimumSize(self, s: QSize) -> None: ...
    def maximumSize(self) -> QSize: ...
    def setMaximumSize(self, w: int, h: int) -> None: ...
    def setMaximumSize(self, s: QSize) -> None: ...
    def minimumWidth(self) -> int: ...
    def setMinimumWidth(self, minw: int) -> None: ...
    def minimumHeight(self) -> int: ...
    def setMinimumHeight(self, minh: int) -> None: ...
    def maximumWidth(self) -> int: ...
    def setMaximumWidth(self, maxw: int) -> None: ...
    def maximumHeight(self) -> int: ...
    def setMaximumHeight(self, maxh: int) -> None: ...
    def sizePolicy(self) -> 'QSizePolicy': ...
    def setSizePolicy(self, policy: 'QSizePolicy') -> None: ...
    def setSizePolicy(self, horizontal: 'QSizePolicy.Policy', vertical: 'QSizePolicy.Policy') -> None: ...
    def update(self) -> None: ...
    def update(self, x: int, y: int, w: int, h: int) -> None: ...
    def update(self, rect: QRect) -> None: ...
    def repaint(self) -> None: ...
    def setFocus(self) -> None: ...
    def clearFocus(self) -> None: ...
    def hasFocus(self) -> bool: ...
    def setWindowTitle(self, title: str) -> None: ...
    def windowTitle(self) -> str: ...
    def setWindowIcon(self, icon: 'QIcon') -> None: ...
    def setCursor(self, cursor: 'QCursor') -> None: ...
    def unsetCursor(self) -> None: ...
    def setMouseTracking(self, enable: bool) -> None: ...
    def hasMouseTracking(self) -> bool: ...
    def setAcceptDrops(self, on: bool) -> None: ...
    def acceptDrops(self) -> bool: ...
    def setAttribute(self, attribute: Qt.WidgetAttribute, on: bool = True) -> None: ...
    def testAttribute(self, attribute: Qt.WidgetAttribute) -> bool: ...
    def setWindowFlags(self, type: Qt.WindowFlags) -> None: ...
    def windowFlags(self) -> Qt.WindowFlags: ...
    def setWindowState(self, state: Qt.WindowStates) -> None: ...
    def windowState(self) -> Qt.WindowStates: ...
    def setStyleSheet(self, styleSheet: str) -> None: ...
    def styleSheet(self) -> str: ...
    def setObjectName(self, name: str) -> None: ...
    def objectName(self) -> str: ...
    def findChild(self, type: type, name: str = ...) -> Optional[Any]: ...
    def findChildren(self, type: type, name: str = ...) -> List[Any]: ...
    def closeEvent(self, event: 'QCloseEvent') -> None: ...
    def showEvent(self, event: 'QShowEvent') -> None: ...
    def hideEvent(self, event: 'QHideEvent') -> None: ...
    def resizeEvent(self, event: 'QResizeEvent') -> None: ...
    def moveEvent(self, event: 'QMoveEvent') -> None: ...
    def paintEvent(self, event: 'QPaintEvent') -> None: ...
    def mousePressEvent(self, event: 'QMouseEvent') -> None: ...
    def mouseReleaseEvent(self, event: 'QMouseEvent') -> None: ...
    def mouseMoveEvent(self, event: 'QMouseEvent') -> None: ...
    def mouseDoubleClickEvent(self, event: 'QMouseEvent') -> None: ...
    def wheelEvent(self, event: 'QWheelEvent') -> None: ...
    def keyPressEvent(self, event: 'QKeyEvent') -> None: ...
    def keyReleaseEvent(self, event: 'QKeyEvent') -> None: ...
    def focusInEvent(self, event: 'QFocusEvent') -> None: ...
    def focusOutEvent(self, event: 'QFocusEvent') -> None: ...
    def enterEvent(self, event: 'QEvent') -> None: ...
    def leaveEvent(self, event: 'QEvent') -> None: ...
    def dragEnterEvent(self, event: 'QDragEnterEvent') -> None: ...
    def dragMoveEvent(self, event: 'QDragMoveEvent') -> None: ...
    def dragLeaveEvent(self, event: 'QDragLeaveEvent') -> None: ...
    def dropEvent(self, event: 'QDropEvent') -> None: ...
    def changeEvent(self, event: 'QEvent') -> None: ...
    def event(self, event: QEvent) -> bool: ...

class QApplication(QObject):
    """应用程序类"""
    def __init__(self, argv: List[str]) -> None: ...
    @staticmethod
    def instance() -> Optional['QApplication']: ...
    def exec_(self) -> int: ...
    def quit(self) -> None: ...
    def primaryScreen(self) -> 'QScreen': ...
    def screens(self) -> List['QScreen']: ...
    def topLevelWindows(self) -> List['QWindow']: ...
    def topLevelWidgets(self) -> List[QWidget]: ...
    def allWidgets(self) -> List[QWidget]: ...
    def setStyle(self, style: 'QStyle') -> None: ...
    def setStyle(self, style: str) -> 'QStyle': ...
    def style(self) -> 'QStyle': ...
    def setPalette(self, palette: 'QPalette') -> None: ...
    def palette(self) -> 'QPalette': ...
    def setFont(self, font: 'QFont') -> None: ...
    def font(self) -> 'QFont': ...
    def setCursorFlashTime(self, duration: int) -> None: ...
    def cursorFlashTime(self) -> int: ...
    def setDoubleClickInterval(self, ms: int) -> None: ...
    def doubleClickInterval(self) -> int: ...
    def setKeyboardInputInterval(self, ms: int) -> None: ...
    def keyboardInputInterval(self) -> int: ...
    def setWheelScrollLines(self) -> int: ...
    def wheelScrollLines(self) -> int: ...
    def setGlobalStrut(self, s: QSize) -> None: ...
    def globalStrut(self) -> QSize: ...
    def setStartDragTime(self, ms: int) -> None: ...
    def startDragTime(self) -> int: ...
    def setStartDragDistance(self, l: int) -> None: ...
    def startDragDistance(self) -> int: ...
    def setQuitOnLastWindowClosed(self, quit: bool) -> None: ...
    def quitOnLastWindowClosed(self) -> bool: ...
    def setWindowIcon(self, icon: 'QIcon') -> None: ...
    def windowIcon(self) -> 'QIcon': ...n    def aboutQt(self) -> None: ...
    def aboutToQuit(self) -> Signal: ...
    def focusChanged(self, old: QWidget, now: QWidget) -> Signal: ...
    def processEvents(self, flags: int = ...) -> None: ...
    def sendEvent(self, receiver: QObject, event: QEvent) -> bool: ...
    def postEvent(self, receiver: QObject, event: QEvent, priority: int = ...) -> None: ...
    def sendPostedEvents(self, receiver: QObject = ..., event_type: int = ...) -> None: ...
    def removePostedEvents(self, receiver: QObject, eventType: int = ...) -> None: ...

class QMainWindow(QWidget):
    """主窗口类"""
    def __init__(self, parent: Optional[QWidget] = None, flags: Qt.WindowFlags = ...) -> None: ...
    def setCentralWidget(self, widget: QWidget) -> None: ...
    def centralWidget(self) -> Optional[QWidget]: ...
    def setMenuBar(self, menuBar: 'QMenuBar') -> None: ...
    def menuBar(self) -> 'QMenuBar': ...
    def setStatusBar(self, statusbar: 'QStatusBar') -> None: ...
    def statusBar(self) -> 'QStatusBar': ...
    def setToolBar(self, toolbar: 'QToolBar') -> None: ...
    def addToolBar(self, toolbar: 'QToolBar') -> None: ...
    def addToolBar(self, title: str) -> 'QToolBar': ...
    def addToolBar(self, area: Qt.ToolBarArea, toolbar: 'QToolBar') -> None: ...
    def insertToolBar(self, before: 'QToolBar', toolbar: 'QToolBar') -> None: ...
    def removeToolBar(self, toolbar: 'QToolBar') -> None: ...
    def setDockOptions(self, options: 'QMainWindow.DockOptions') -> None: ...
    def dockOptions(self) -> 'QMainWindow.DockOptions': ...
    def setCorner(self, corner: Qt.Corner, area: Qt.DockWidgetArea) -> None: ...
    def corner(self, corner: Qt.Corner) -> Qt.DockWidgetArea: ...
    def setDocumentMode(self, enabled: bool) -> None: ...
    def documentMode(self) -> bool: ...
    def setTabPosition(self, areas: Qt.DockWidgetAreas, tabPosition: 'QTabWidget.TabPosition') -> None: ...
    def tabPosition(self, area: Qt.DockWidgetArea) -> 'QTabWidget.TabPosition': ...
    def setTabShape(self, tabShape: 'QTabWidget.TabShape') -> None: ...
    def tabShape(self) -> 'QTabWidget.TabShape': ...
    def setAnimated(self, enabled: bool) -> None: ...
    def isAnimated(self) -> bool: ...
    def setDockNestingEnabled(self, enabled: bool) -> None: ...
    def isDockNestingEnabled(self) -> bool: ...
    def addDockWidget(self, area: Qt.DockWidgetArea, dockwidget: 'QDockWidget') -> None: ...
    def addDockWidget(self, area: Qt.DockWidgetArea, dockwidget: 'QDockWidget', orientation: Qt.Orientation) -> None: ...
    def splitDockWidget(self, after: 'QDockWidget', dockwidget: 'QDockWidget', orientation: Qt.Orientation) -> None: ...
    def tabifyDockWidget(self, first: 'QDockWidget', second: 'QDockWidget') -> None: ...
    def removeDockWidget(self, dockwidget: 'QDockWidget') -> None: ...
    def restoreDockWidget(self, dockwidget: 'QDockWidget') -> bool: ...
    def setUnifiedTitleAndToolBarOnMac(self, set: bool) -> None: ...
    def unifiedTitleAndToolBarOnMac(self) -> bool: ...
    def toolBarArea(self, toolbar: 'QToolBar') -> Qt.ToolBarArea: ...
    def toolBarBreak(self, toolbar: 'QToolBar') -> bool: ...
    def addToolBarBreak(self, area: Qt.ToolBarArea = ...) -> None: ...
    def insertToolBarBreak(self, before: 'QToolBar') -> None: ...
    def removeToolBarBreak(self, before: 'QToolBar') -> None: ...

class QMessageBox(QDialog):
    """消息框类"""
    # 消息框类型
    NoIcon: int
    Question: int
    Information: int
    Warning: int
    Critical: int
    
    # 标准按钮
    NoButton: int
    Ok: int
    Save: int
    SaveAll: int
    Open: int
    Yes: int
    YesToAll: int
    No: int
    NoToAll: int
    Abort: int
    Retry: int
    Ignore: int
    Close: int
    Cancel: int
    Discard: int
    Help: int
    Apply: int
    Reset: int
    RestoreDefaults: int
    
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setInformativeText(self, text: str) -> None: ...
    def informativeText(self) -> str: ...
    def setDetailedText(self, text: str) -> None: ...
    def detailedText(self) -> str: ...
    def setIcon(self, icon: 'QMessageBox.Icon') -> None: ...
    def icon(self) -> 'QMessageBox.Icon': ...
    def setIconPixmap(self, pixmap: 'QPixmap') -> None: ...
    def iconPixmap(self) -> 'QPixmap': ...
    def setStandardButtons(self, buttons: 'QMessageBox.StandardButtons') -> None: ...
    def standardButtons(self) -> 'QMessageBox.StandardButtons': ...
    def setDefaultButton(self, button: 'QMessageBox.StandardButton') -> None: ...
    def setDefaultButton(self, button: 'QPushButton') -> None: ...
    def defaultButton(self) -> 'QPushButton': ...
    def setEscapeButton(self, button: 'QMessageBox.StandardButton') -> None: ...
    def setEscapeButton(self, button: 'QPushButton') -> None: ...
    def escapeButton(self) -> 'QPushButton': ...n    def setWindowTitle(self, title: str) -> None: ...
    def setWindowModality(self, windowModality: Qt.WindowModality) -> None: ...
    @staticmethod
    def critical(parent: Optional[QWidget], title: str, text: str, buttons: 'QMessageBox.StandardButtons' = ..., defaultButton: 'QMessageBox.StandardButton' = ...) -> 'QMessageBox.StandardButton': ...
    @staticmethod
    def information(parent: Optional[QWidget], title: str, text: str, buttons: 'QMessageBox.StandardButtons' = ..., defaultButton: 'QMessageBox.StandardButton' = ...) -> 'QMessageBox.StandardButton': ...
    @staticmethod
    def question(parent: Optional[QWidget], title: str, text: str, buttons: 'QMessageBox.StandardButtons' = ..., defaultButton: 'QMessageBox.StandardButton' = ...) -> 'QMessageBox.StandardButton': ...
    @staticmethod
    def warning(parent: Optional[QWidget], title: str, text: str, buttons: 'QMessageBox.StandardButtons' = ..., defaultButton: 'QMessageBox.StandardButton' = ...) -> 'QMessageBox.StandardButton': ...
    @staticmethod
    def about(parent: Optional[QWidget], title: str, text: str) -> None: ...
    @staticmethod
    def aboutQt(parent: Optional[QWidget], title: str = ...) -> None: ...

class QDialog(QWidget):
    """对话框基类"""
    Accepted: int
    Rejected: int
    
    def __init__(self, parent: Optional[QWidget] = None, flags: Qt.WindowFlags = ...) -> None: ...
    def result(self) -> int: ...
    def setResult(self, r: int) -> None: ...
    def open(self) -> None: ...
    def exec_(self) -> int: ...
    def done(self, r: int) -> None: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...
    def showEvent(self, event: 'QShowEvent') -> None: ...
    def closeEvent(self, event: 'QCloseEvent') -> None: ...
    def setModal(self, modal: bool) -> None: ...
    def isModal(self) -> bool: ...
    def setSizeGripEnabled(self, enabled: bool) -> None: ...
    def isSizeGripEnabled(self) -> bool: ...
    def finished(self, result: int) -> Signal: ...
    def accepted(self) -> Signal: ...
    def rejected(self) -> Signal: ...

class QVBoxLayout:
    """垂直布局"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addWidget(self, w: QWidget, stretch: int = ..., alignment: Qt.Alignment = ...) -> None: ...
    def addLayout(self, layout: 'QLayout', stretch: int = ...) -> None: ...
    def addStretch(self, stretch: int = 1) -> None: ...
    def addSpacing(self, size: int) -> None: ...
    def setSpacing(self, spacing: int) -> None: ...
    def spacing(self) -> int: ...
    def setContentsMargins(self, left: int, top: int, right: int, bottom: int) -> None: ...
    def contentsMargins(self) -> 'QMargins': ...
    def setAlignment(self, alignment: Qt.Alignment) -> None: ...

class QHBoxLayout:
    """水平布局"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addWidget(self, w: QWidget, stretch: int = ..., alignment: Qt.Alignment = ...) -> None: ...
    def addLayout(self, layout: 'QLayout', stretch: int = ...) -> None: ...
    def addStretch(self, stretch: int = 1) -> None: ...
    def addSpacing(self, size: int) -> None: ...
    def setSpacing(self, spacing: int) -> None: ...
    def spacing(self) -> int: ...
    def setContentsMargins(self, left: int, top: int, right: int, bottom: int) -> None: ...
    def contentsMargins(self) -> 'QMargins': ...
    def setAlignment(self, alignment: Qt.Alignment) -> None: ...

class QLabel(QWidget):
    """标签控件"""
    def __init__(self, parent: Optional[QWidget] = None, flags: Qt.WindowFlags = ...) -> None: ...
    def __init__(self, text: str, parent: Optional[QWidget] = None, flags: Qt.WindowFlags = ...) -> None: ...
    def text(self) -> str: ...
    def setText(self, text: str) -> None: ...
    def setPixmap(self, pixmap: 'QPixmap') -> None: ...
    def setMovie(self, movie: 'QMovie') -> None: ...
    def setNum(self, num: int) -> None: ...
    def setNum(self, num: float) -> None: ...
    def clear(self) -> None: ...
    def setAlignment(self, alignment: Qt.Alignment) -> None: ...
    def alignment(self) -> Qt.Alignment: ...
    def setWordWrap(self, on: bool) -> None: ...
    def wordWrap(self) -> bool: ...
    def setIndent(self, indent: int) -> None: ...
    def indent(self) -> int: ...
    def setMargin(self, margin: int) -> None: ...
    def margin(self) -> int: ...
    def setScaledContents(self, scaled: bool) -> None: ...
    def hasScaledContents(self) -> bool: ...
    def setOpenExternalLinks(self, open: bool) -> None: ...
    def openExternalLinks(self) -> bool: ...
    def setTextInteractionFlags(self, flags: Qt.TextInteractionFlags) -> None: ...
    def textInteractionFlags(self) -> Qt.TextInteractionFlags: ...
    def setSelection(self, start: int, length: int) -> None: ...
    def selectedText(self) -> str: ...
    def linkActivated(self, link: str) -> Signal: ...
    def linkHovered(self, link: str) -> Signal: ...

class QPushButton(QWidget):
    """按钮控件"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def __init__(self, text: str, parent: Optional[QWidget] = None) -> None: ...
    def __init__(self, icon: 'QIcon', text: str, parent: Optional[QWidget] = None) -> None: ...
    def text(self) -> str: ...
    def setText(self, text: str) -> None: ...
    def setIcon(self, icon: 'QIcon') -> None: ...
    def icon(self) -> 'QIcon': ...
    def setIconSize(self, size: QSize) -> None: ...
    def iconSize(self) -> QSize: ...
    def setShortcut(self, key: 'QKeySequence') -> None: ...
    def shortcut(self) -> 'QKeySequence': ...
    def setCheckable(self, checkable: bool) -> None: ...
    def isCheckable(self) -> bool: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def setDown(self, down: bool) -> None: ...
    def isDown(self) -> bool: ...
    def setAutoDefault(self, auto: bool) -> None: ...
    def autoDefault(self) -> bool: ...
    def setDefault(self, default: bool) -> None: ...
    def isDefault(self) -> bool: ...
    def setFlat(self, flat: bool) -> None: ...
    def isFlat(self) -> bool: ...
    def clicked(self, checked: bool = ...) -> Signal: ...
    def pressed(self) -> Signal: ...
    def released(self) -> Signal: ...
    def toggled(self, checked: bool) -> Signal: ...
    def showMenu(self) -> None: ...
    def setMenu(self, menu: 'QMenu') -> None: ...
    def menu(self) -> 'QMenu': ...
    def setAutoRepeat(self, auto: bool) -> None: ...
    def autoRepeat(self) -> bool: ...
    def setAutoRepeatDelay(self, delay: int) -> None: ...
    def autoRepeatDelay(self) -> int: ...
    def setAutoRepeatInterval(self, interval: int) -> None: ...
    def autoRepeatInterval(self) -> int: ...

class QLineEdit(QWidget):
    """单行文本输入框"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def __init__(self, text: str, parent: Optional[QWidget] = None) -> None: ...
    def text(self) -> str: ...
    def setText(self, text: str) -> None: ...
    def clear(self) -> None: ...
    def selectAll(self) -> None: ...
    def setMaxLength(self, maxLength: int) -> None: ...
    def maxLength(self) -> int: ...
    def setReadOnly(self, readOnly: bool) -> None: ...
    def isReadOnly(self) -> bool: ...
    def setPlaceholderText(self, placeholder: str) -> None: ...
    def placeholderText(self) -> str: ...
    def setEchoMode(self, mode: 'QLineEdit.EchoMode') -> None: ...
    def echoMode(self) -> 'QLineEdit.EchoMode': ...
    def setAlignment(self, alignment: Qt.Alignment) -> None: ...
    def alignment(self) -> Qt.Alignment: ...
    def setValidator(self, validator: 'QValidator') -> None: ...
    def validator(self) -> 'QValidator': ...
    def setCompleter(self, completer: 'QCompleter') -> None: ...
    def completer(self) -> 'QCompleter': ...
    def textChanged(self, text: str) -> Signal: ...
    def textEdited(self, text: str) -> Signal: ...
    def cursorPositionChanged(self, oldPos: int, newPos: int) -> Signal: ...
    def returnPressed(self) -> Signal: ...
    def editingFinished(self) -> Signal: ...
    def selectionChanged(self) -> Signal: ...

class QTextEdit(QWidget):
    """多行文本编辑框"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def __init__(self, text: str, parent: Optional[QWidget] = None) -> None: ...
    def toPlainText(self) -> str: ...
    def setPlainText(self, text: str) -> None: ...
    def toHtml(self) -> str: ...
    def setHtml(self, text: str) -> None: ...
    def clear(self) -> None: ...
    def setReadOnly(self, readOnly: bool) -> None: ...
    def isReadOnly(self) -> bool: ...
    def setPlaceholderText(self, placeholder: str) -> None: ...
    def placeholderText(self) -> str: ...
    def textChanged(self) -> Signal: ...
    def selectionChanged(self) -> Signal: ...
    def cursorPositionChanged(self) -> Signal: ...
    def copy(self) -> None: ...
    def cut(self) -> None: ...
    def paste(self) -> None: ...
    def undo(self) -> None: ...
    def redo(self) -> None: ...
    def selectAll(self) -> None: ...
    def insertPlainText(self, text: str) -> None: ...
    def append(self, text: str) -> None: ...

class QComboBox(QWidget):
    """下拉框"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def count(self) -> int: ...
    def addItem(self, text: str, userData: Any = ...) -> None: ...
    def addItem(self, icon: 'QIcon', text: str, userData: Any = ...) -> None: ...
    def addItems(self, texts: List[str]) -> None: ...
    def insertItem(self, index: int, text: str, userData: Any = ...) -> None: ...
    def insertItem(self, index: int, icon: 'QIcon', text: str, userData: Any = ...) -> None: ...
    def insertItems(self, index: int, texts: List[str]) -> None: ...
    def removeItem(self, index: int) -> None: ...
    def clear(self) -> None: ...
    def currentIndex(self) -> int: ...
    def currentText(self) -> str: ...
    def currentData(self, role: int = ...) -> Any: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def setCurrentText(self, text: str) -> None: ...
    def itemText(self, index: int) -> str: ...
    def itemData(self, index: int, role: int = ...) -> Any: ...
    def setItemData(self, index: int, value: Any, role: int = ...) -> None: ...
    def setItemText(self, index: int, text: str) -> None: ...
    def setEditable(self, editable: bool) -> None: ...
    def isEditable(self) -> bool: ...
    def setMaxCount(self, max: int) -> None: ...
    def maxCount(self) -> int: ...
    def setMaxVisibleItems(self, maxItems: int) -> None: ...
    def maxVisibleItems(self) -> int: ...
    def setMinimumContentsLength(self, characters: int) -> None: ...
    def minimumContentsLength(self) -> int: ...
    def currentIndexChanged(self, index: int) -> Signal: ...
    def currentTextChanged(self, text: str) -> Signal: ...
    def activated(self, index: int) -> Signal: ...
    def textActivated(self, text: str) -> Signal: ...
    def highlighted(self, index: int) -> Signal: ...

class QTableWidget(QAbstractItemModel):
    """表格控件"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def __init__(self, rows: int, columns: int, parent: Optional[QWidget] = None) -> None: ...
    def rowCount(self) -> int: ...
    def columnCount(self) -> int: ...
    def setRowCount(self, rows: int) -> None: ...
    def setColumnCount(self, columns: int) -> None: ...
    def insertRow(self, row: int) -> None: ...
    def insertColumn(self, column: int) -> None: ...
    def removeRow(self, row: int) -> None: ...
    def removeColumn(self, column: int) -> None: ...
    def clear(self) -> None: ...
    def clearContents(self) -> None: ...
    def item(self, row: int, column: int) -> Optional['QTableWidgetItem']: ...
    def setItem(self, row: int, column: int, item: 'QTableWidgetItem') -> None: ...
    def takeItem(self, row: int, column: int) -> 'QTableWidgetItem': ...
    def verticalHeaderItem(self, row: int) -> 'QTableWidgetItem': ...
    def setVerticalHeaderItem(self, row: int, item: 'QTableWidgetItem') -> None: ...
    def horizontalHeaderItem(self, column: int) -> 'QTableWidgetItem': ...
    def setHorizontalHeaderItem(self, column: int, item: 'QTableWidgetItem') -> None: ...
    def setHorizontalHeaderLabels(self, labels: List[str]) -> None: ...
    def setVerticalHeaderLabels(self, labels: List[str]) -> None: ...
    def currentRow(self) -> int: ...
    def currentColumn(self) -> int: ...
    def currentItem(self) -> Optional['QTableWidgetItem']: ...
    def setCurrentItem(self, item: 'QTableWidgetItem') -> None: ...
    def setCurrentCell(self, row: int, column: int) -> None: ...
    def itemAt(self, p: QPoint) -> Optional['QTableWidgetItem']: ...
    def itemAt(self, x: int, y: int) -> Optional['QTableWidgetItem']: ...
    def visualItemRect(self, item: 'QTableWidgetItem') -> QRect: ...
    def sortItems(self, column: int, order: Qt.SortOrder = ...) -> None: ...
    def setSortingEnabled(self, enable: bool) -> None: ...
    def isSortingEnabled(self) -> bool: ...
    def editItem(self, item: 'QTableWidgetItem') -> None: ...
    def openPersistentEditor(self, item: 'QTableWidgetItem') -> None: ...
    def closePersistentEditor(self, item: 'QTableWidgetItem') -> None: ...
    def cellWidget(self, row: int, column: int) -> QWidget: ...
    def setCellWidget(self, row: int, column: int, widget: QWidget) -> None: ...
    def removeCellWidget(self, row: int, column: int) -> None: ...
    def itemChanged(self, item: 'QTableWidgetItem') -> Signal: ...
    def currentItemChanged(self, current: 'QTableWidgetItem', previous: 'QTableWidgetItem') -> Signal: ...
    def itemClicked(self, item: 'QTableWidgetItem') -> Signal: ...
    def itemDoubleClicked(self, item: 'QTableWidgetItem') -> Signal: ...
    def itemEntered(self, item: 'QTableWidgetItem') -> Signal: ...
    def itemPressed(self, item: 'QTableWidgetItem') -> Signal: ...
    def itemSelectionChanged(self) -> Signal: ...
    def cellClicked(self, row: int, column: int) -> Signal: ...
    def cellDoubleClicked(self, row: int, column: int) -> Signal: ...
    def cellEntered(self, row: int, column: int) -> Signal: ...
    def cellPressed(self, row: int, column: int) -> Signal: ...
    def currentCellChanged(self, currentRow: int, currentColumn: int, previousRow: int, previousColumn: int) -> Signal: ...
    def horizontalHeader(self) -> 'QHeaderView': ...
    def verticalHeader(self) -> 'QHeaderView': ...
    def setSelectionMode(self, mode: 'QAbstractItemView.SelectionMode') -> None: ...
    def selectionMode(self) -> 'QAbstractItemView.SelectionMode': ...
    def setSelectionBehavior(self, behavior: 'QAbstractItemView.SelectionBehavior') -> None: ...
    def selectionBehavior(self) -> 'QAbstractItemView.SelectionBehavior': ...

class QTreeWidget:
    """树形控件"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addTopLevelItem(self, item: 'QTreeWidgetItem') -> None: ...
    def insertTopLevelItem(self, index: int, item: 'QTreeWidgetItem') -> None: ...
    def takeTopLevelItem(self, index: int) -> 'QTreeWidgetItem': ...
    def topLevelItem(self, index: int) -> 'QTreeWidgetItem': ...
    def topLevelItemCount(self) -> int: ...
    def clear(self) -> None: ...
    def currentItem(self) -> Optional['QTreeWidgetItem']: ...
    def setCurrentItem(self, item: 'QTreeWidgetItem') -> None: ...
    def itemAt(self, p: QPoint) -> Optional['QTreeWidgetItem']: ...
    def itemWidget(self, item: 'QTreeWidgetItem', column: int) -> QWidget: ...
    def setItemWidget(self, item: 'QTreeWidgetItem', column: int, widget: QWidget) -> None: ...
    def removeItemWidget(self, item: 'QTreeWidgetItem', column: int) -> None: ...
    def selectedItems(self) -> List['QTreeWidgetItem']: ...
    def findItems(self, text: str, flags: Qt.MatchFlags, column: int = ...) -> List['QTreeWidgetItem']: ...
    def sortItems(self, column: int, order: Qt.SortOrder) -> None: ...
    def setColumnCount(self, columns: int) -> None: ...
    def columnCount(self) -> int: ...
    def setHeaderLabel(self, label: str) -> None: ...
    def setHeaderLabels(self, labels: List[str]) -> None: ...
    def headerItem(self) -> 'QTreeWidgetItem': ...
    def setHeaderItem(self, item: 'QTreeWidgetItem') -> None: ...
    def invisibleRootItem(self) -> 'QTreeWidgetItem': ...
    def setSelectionMode(self, mode: 'QAbstractItemView.SelectionMode') -> None: ...
    def currentItemChanged(self, current: 'QTreeWidgetItem', previous: 'QTreeWidgetItem') -> Signal: ...
    def itemClicked(self, item: 'QTreeWidgetItem', column: int) -> Signal: ...
    def itemDoubleClicked(self, item: 'QTreeWidgetItem', column: int) -> Signal: ...

class QListWidget:
    """列表控件"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addItem(self, item: 'QListWidgetItem') -> None: ...
    def addItem(self, label: str) -> None: ...
    def addItems(self, labels: List[str]) -> None: ...
    def insertItem(self, row: int, item: 'QListWidgetItem') -> None: ...
    def insertItem(self, row: int, label: str) -> None: ...
    def insertItems(self, row: int, labels: List[str]) -> None: ...
    def takeItem(self, row: int) -> 'QListWidgetItem': ...
    def item(self, row: int) -> 'QListWidgetItem': ...
    def count(self) -> int: ...
    def row(self, item: 'QListWidgetItem') -> int: ...
    def currentRow(self) -> int: ...
    def setCurrentRow(self, row: int) -> None: ...
    def currentItem(self) -> Optional['QListWidgetItem']: ...
    def setCurrentItem(self, item: 'QListWidgetItem') -> None: ...
    def clear(self) -> None: ...
    def selectedItems(self) -> List['QListWidgetItem']: ...
    def findItems(self, text: str, flags: Qt.MatchFlags) -> List['QListWidgetItem']: ...
    def sortItems(self, order: Qt.SortOrder = ...) -> None: ...
    def itemWidget(self, item: 'QListWidgetItem') -> QWidget: ...
    def setItemWidget(self, item: 'QListWidgetItem', widget: QWidget) -> None: ...
    def removeItemWidget(self, item: 'QListWidgetItem') -> None: ...
    def setSelectionMode(self, mode: 'QAbstractItemView.SelectionMode') -> None: ...
    def currentRowChanged(self, currentRow: int) -> Signal: ...
    def currentItemChanged(self, current: 'QListWidgetItem', previous: 'QListWidgetItem') -> Signal: ...
    def currentTextChanged(self, currentText: str) -> Signal: ...
    def itemClicked(self, item: 'QListWidgetItem') -> Signal: ...
    def itemDoubleClicked(self, item: 'QListWidgetItem') -> Signal: ...
    def itemEntered(self, item: 'QListWidgetItem') -> Signal: ...
    def itemPressed(self, item: 'QListWidgetItem') -> Signal: ...

class QProgressBar(QWidget):
    """进度条"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def minimum(self) -> int: ...
    def maximum(self) -> int: ...
    def value(self) -> int: ...
    def setMinimum(self, minimum: int) -> None: ...
    def setMaximum(self, maximum: int) -> None: ...
    def setValue(self, value: int) -> None: ...
    def setRange(self, minimum: int, maximum: int) -> None: ...
    def reset(self) -> None: ...
    def setTextVisible(self, visible: bool) -> None: ...
    def isTextVisible(self) -> bool: ...
    def text(self) -> str: ...
    def setFormat(self, format: str) -> None: ...
    def format(self) -> str: ...
    def setInvertedAppearance(self, invert: bool) -> None: ...
    def invertedAppearance(self) -> bool: ...
    def setOrientation(self, orientation: Qt.Orientation) -> None: ...
    def orientation(self) -> Qt.Orientation: ...
    def setAlignment(self, alignment: Qt.Alignment) -> None: ...
    def valueChanged(self, value: int) -> Signal: ...

class QScrollBar(QWidget):
    """滚动条"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def __init__(self, orientation: Qt.Orientation, parent: Optional[QWidget] = None) -> None: ...
    def minimum(self) -> int: ...
    def maximum(self) -> int: ...
    def value(self) -> int: ...
    def setMinimum(self, min: int) -> None: ...
    def setMaximum(self, max: int) -> None: ...
    def setValue(self, value: int) -> None: ...
    def setRange(self, min: int, max: int) -> None: ...
    def singleStep(self) -> int: ...
    def setSingleStep(self, step: int) -> None: ...
    def pageStep(self) -> int: ...
    def setPageStep(self, step: int) -> None: ...
    def setOrientation(self, orientation: Qt.Orientation) -> None: ...
    def orientation(self) -> Qt.Orientation: ...
    def valueChanged(self, value: int) -> Signal: ...
    def sliderPressed(self) -> Signal: ...
    def sliderMoved(self, position: int) -> Signal: ...
    def sliderReleased(self) -> Signal: ...

class QGroupBox(QWidget):
    """分组框"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def __init__(self, title: str, parent: Optional[QWidget] = None) -> None: ...
    def title(self) -> str: ...
    def setTitle(self, title: str) -> None: ...
    def isCheckable(self) -> bool: ...
    def setCheckable(self, checkable: bool) -> None: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def isFlat(self) -> bool: ...
    def setFlat(self, flat: bool) -> None: ...
    def alignment(self) -> Qt.Alignment: ...
    def setAlignment(self, alignment: int) -> None: ...
    def clicked(self, checked: bool = ...) -> Signal: ...
    def toggled(self, checked: bool) -> Signal: ...

class QTabWidget(QWidget):
    """选项卡控件"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addTab(self, widget: QWidget, label: str) -> int: ...
    def addTab(self, widget: QWidget, icon: 'QIcon', label: str) -> int: ...
    def insertTab(self, index: int, widget: QWidget, label: str) -> int: ...
    def insertTab(self, index: int, widget: QWidget, icon: 'QIcon', label: str) -> int: ...
    def removeTab(self, index: int) -> None: ...
    def clear(self) -> None: ...
    def count(self) -> int: ...
    def currentIndex(self) -> int: ...
    def currentWidget(self) -> QWidget: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def setCurrentWidget(self, widget: QWidget) -> None: ...
    def indexOf(self, widget: QWidget) -> int: ...
    def widget(self, index: int) -> QWidget: ...
    def tabText(self, index: int) -> str: ...
    def setTabText(self, index: int, label: str) -> None: ...
    def tabIcon(self, index: int) -> 'QIcon': ...
    def setTabIcon(self, index: int, icon: 'QIcon') -> None: ...
    def setTabEnabled(self, index: int, enabled: bool) -> None: ...
    def isTabEnabled(self, index: int) -> bool: ...
    def setTabVisible(self, index: int, visible: bool) -> None: ...
    def isTabVisible(self, index: int) -> bool: ...
    def setTabToolTip(self, index: int, tip: str) -> None: ...
    def tabToolTip(self, index: int) -> str: ...
    def setTabWhatsThis(self, index: int, text: str) -> None: ...
    def tabWhatsThis(self, index: int) -> str: ...
    def setTabsClosable(self, closeable: bool) -> None: ...
    def tabsClosable(self) -> bool: ...
    def setMovable(self, movable: bool) -> None: ...
    def isMovable(self) -> bool: ...
    def setDocumentMode(self, set: bool) -> None: ...
    def documentMode(self) -> bool: ...
    def setTabBarAutoHide(self, enabled: bool) -> None: ...
    def tabBarAutoHide(self) -> bool: ...
    def setUsesScrollButtons(self, useButtons: bool) -> None: ...
    def usesScrollButtons(self) -> bool: ...
    def currentChanged(self, index: int) -> Signal: ...
    def tabCloseRequested(self, index: int) -> Signal: ...
    def tabBarClicked(self, index: int) -> Signal: ...
    def tabBarDoubleClicked(self, index: int) -> Signal: ...

class QFrame(QWidget):
    """框架控件"""
    NoFrame: int
    Box: int
    Panel: int
    WinPanel: int
    HLine: int
    VLine: int
    StyledPanel: int
    
    def __init__(self, parent: Optional[QWidget] = None, flags: Qt.WindowFlags = ...) -> None: ...
    def frameStyle(self) -> int: ...
    def setFrameStyle(self, style: int) -> None: ...
    def frameWidth(self) -> int: ...
    def frameShape(self) -> 'QFrame.Shape': ...
    def setFrameShape(self, shape: 'QFrame.Shape') -> None: ...
    def frameShadow(self) -> 'QFrame.Shadow': ...
    def setFrameShadow(self, shadow: 'QFrame.Shadow') -> None: ...
    def lineWidth(self) -> int: ...
    def setLineWidth(self, width: int) -> None: ...
    def midLineWidth(self) -> int: ...
    def setMidLineWidth(self, width: int) -> None: ...

class QSplitter(QWidget):
    """分割器"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def __init__(self, orientation: Qt.Orientation, parent: Optional[QWidget] = None) -> None: ...
    def addWidget(self, widget: QWidget) -> None: ...
    def insertWidget(self, index: int, widget: QWidget) -> None: ...
    def widget(self, index: int) -> QWidget: ...
    def indexOf(self, widget: QWidget) -> int: ...
    def count(self) -> int: ...
    def sizes(self) -> List[int]: ...
    def setSizes(self, sizes: List[int]) -> None: ...
    def getRange(self, index: int) -> Tuple[int, int]: ...
    def handle(self, index: int) -> 'QSplitterHandle': ...
    def setOrientation(self, orientation: Qt.Orientation) -> None: ...
    def orientation(self) -> Qt.Orientation: ...
    def setOpaqueResize(self, opaque: bool = True) -> None: ...
    def opaqueResize(self) -> bool: ...
    def setHandleWidth(self, width: int) -> None: ...
    def handleWidth(self) -> int: ...
    def setChildrenCollapsible(self, collapsible: bool) -> None: ...
    def childrenCollapsible(self) -> bool: ...
    def setCollapsible(self, index: int, collapse: bool) -> None: ...
    def isCollapsible(self, index: int) -> bool: ...
    def setStretchFactor(self, index: int, stretch: int) -> None: ...
    def refresh(self) -> None: ...
    def splitterMoved(self, pos: int, index: int) -> Signal: ...

class QStackedWidget(QWidget):
    """堆叠控件"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addWidget(self, widget: QWidget) -> int: ...
    def insertWidget(self, index: int, widget: QWidget) -> int: ...
    def removeWidget(self, widget: QWidget) -> None: ...
    def widget(self, index: int) -> QWidget: ...
    def currentWidget(self) -> QWidget: ...
    def currentIndex(self) -> int: ...
    def setCurrentWidget(self, widget: QWidget) -> None: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def count(self) -> int: ...
    def indexOf(self, widget: QWidget) -> int: ...
    def currentChanged(self, index: int) -> Signal: ...
    def widgetRemoved(self, index: int) -> Signal: ...

class QMenuBar(QWidget):
    """菜单栏"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addMenu(self, menu: 'QMenu') -> 'QAction': ...
    def addMenu(self, title: str) -> 'QMenu': ...
    def addMenu(self, icon: 'QIcon', title: str) -> 'QMenu': ...
    def addAction(self, action: 'QAction') -> None: ...
    def addAction(self, text: str) -> 'QAction': ...
    def addAction(self, text: str, receiver: QObject, member: bytes) -> 'QAction': ...
    def addSeparator(self) -> 'QAction': ...
    def insertMenu(self, before: 'QAction', menu: 'QMenu') -> 'QAction': ...
    def insertSeparator(self, before: 'QAction') -> 'QAction': ...
    def removeAction(self, action: 'QAction') -> None: ...
    def clear(self) -> None: ...
    def activeAction(self) -> 'QAction': ...
    def setActiveAction(self, action: 'QAction') -> None: ...
    def cornerWidget(self, corner: Qt.Corner = ...) -> QWidget: ...
    def setCornerWidget(self, w: QWidget, corner: Qt.Corner = ...) -> None: ...
    def defaultUp(self) -> bool: ...
    def setDefaultUp(self, defaultUp: bool) -> None: ...
    def nativeMenuBar(self) -> bool: ...
    def setNativeMenuBar(self, nativeMenuBar: bool) -> None: ...
    def triggered(self, action: 'QAction') -> Signal: ...
    def hovered(self, action: 'QAction') -> Signal: ...

class QStatusBar(QWidget):
    """状态栏"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addWidget(self, widget: QWidget, stretch: int = ...) -> None: ...
    def insertWidget(self, index: int, widget: QWidget, stretch: int = ...) -> None: ...
    def addPermanentWidget(self, widget: QWidget, stretch: int = ...) -> None: ...
    def insertPermanentWidget(self, index: int, widget: QWidget, stretch: int = ...) -> None: ...
    def removeWidget(self, widget: QWidget) -> None: ...
    def showMessage(self, text: str, timeout: int = 0) -> None: ...
    def clearMessage(self) -> None: ...
    def currentMessage(self) -> str: ...
    def setSizeGripEnabled(self, enabled: bool) -> None: ...
    def isSizeGripEnabled(self) -> bool: ...
    def messageChanged(self, message: str) -> Signal: ...

class QToolBar(QWidget):
    """工具栏"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def __init__(self, title: str, parent: Optional[QWidget] = None) -> None: ...
    def addAction(self, action: 'QAction') -> None: ...
    def addAction(self, text: str) -> 'QAction': ...
    def addAction(self, text: str, receiver: QObject, member: bytes) -> 'QAction': ...
    def addAction(self, icon: 'QIcon', text: str) -> 'QAction': ...
    def addAction(self, icon: 'QIcon', text: str, receiver: QObject, member: bytes) -> 'QAction': ...
    def addSeparator(self) -> 'QAction': ...
    def insertSeparator(self, before: 'QAction') -> 'QAction': ...
    def addStretch(self, stretch: int = 1) -> 'QAction': ...
    def insertStretch(self, before: 'QAction', stretch: int = 1) -> 'QAction': ...
    def addWidget(self, widget: QWidget) -> 'QAction': ...
    def insertWidget(self, before: 'QAction', widget: QWidget) -> 'QAction': ...
    def removeAction(self, action: 'QAction') -> None: ...
    def clear(self) -> None: ...
    def setOrientation(self, orientation: Qt.Orientation) -> None: ...
    def orientation(self) -> Qt.Orientation: ...
    def setToolButtonStyle(self, toolButtonStyle: Qt.ToolButtonStyle) -> None: ...
    def toolButtonStyle(self) -> Qt.ToolButtonStyle: ...
    def setMovable(self, movable: bool) -> None: ...
    def isMovable(self) -> bool: ...
    def setFloatable(self, floatable: bool) -> None: ...
    def isFloatable(self) -> bool: ...
    def setAllowedAreas(self, areas: Qt.ToolBarAreas) -> None: ...
    def allowedAreas(self) -> Qt.ToolBarAreas: ...
    def isAreaAllowed(self, area: Qt.ToolBarArea) -> bool: ...
    def setIconSize(self, iconSize: QSize) -> None: ...
    def iconSize(self) -> QSize: ...
    def actionTriggered(self, action: 'QAction') -> Signal: ...
    def movableChanged(self, movable: bool) -> Signal: ...
    def allowedAreasChanged(self, allowedAreas: Qt.ToolBarAreas) -> Signal: ...
    def orientationChanged(self, orientation: Qt.Orientation) -> Signal: ...
    def iconSizeChanged(self, iconSize: QSize) -> Signal: ...
    def toolButtonStyleChanged(self, toolButtonStyle: Qt.ToolButtonStyle) -> Signal: ...
    def topLevelChanged(self, topLevel: bool) -> Signal: ...
    def visibilityChanged(self, visible: bool) -> Signal: ...

class QDockWidget(QWidget):
    """停靠窗口"""
    def __init__(self, parent: Optional[QWidget] = None, flags: Qt.WindowFlags = ...) -> None: ...
    def __init__(self, title: str, parent: Optional[QWidget] = None, flags: Qt.WindowFlags = ...) -> None: ...
    def widget(self) -> QWidget: ...
    def setWidget(self, widget: QWidget) -> None: ...
    def titleBarWidget(self) -> QWidget: ...
    def setTitleBarWidget(self, widget: QWidget) -> None: ...
    def isFloating(self) -> bool: ...
    def setFloating(self, floating: bool) -> None: ...
    def features(self) -> 'QDockWidget.DockWidgetFeatures': ...
    def setFeatures(self, features: 'QDockWidget.DockWidgetFeatures') -> None: ...
    def allowedAreas(self) -> Qt.DockWidgetAreas: ...
    def setAllowedAreas(self, areas: Qt.DockWidgetAreas) -> None: ...
    def toggleViewAction(self) -> 'QAction': ...
    def featuresChanged(self, features: 'QDockWidget.DockWidgetFeatures') -> Signal: ...
    def topLevelChanged(self, topLevel: bool) -> Signal: ...
    def allowedAreasChanged(self, allowedAreas: Qt.DockWidgetAreas) -> Signal: ...
    def visibilityChanged(self, visible: bool) -> Signal: ...
    def dockLocationChanged(self, area: Qt.DockWidgetArea) -> Signal: ...

class QMenu(QWidget):
    """菜单"""
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def __init__(self, title: str, parent: Optional[QWidget] = None) -> None: ...
    def addAction(self, action: 'QAction') -> None: ...
    def addAction(self, text: str) -> 'QAction': ...
    def addAction(self, text: str, receiver: QObject, member: bytes, shortcut: 'QKeySequence' = ...) -> 'QAction': ...
    def addAction(self, icon: 'QIcon', text: str) -> 'QAction': ...
    def addAction(self, icon: 'QIcon', text: str, receiver: QObject, member: bytes, shortcut: 'QKeySequence' = ...) -> 'QAction': ...
    def addMenu(self, menu: 'QMenu') -> 'QAction': ...
    def addMenu(self, title: str) -> 'QMenu': ...
    def addMenu(self, icon: 'QIcon', title: str) -> 'QMenu': ...
    def addSeparator(self) -> 'QAction': ...
    def insertSeparator(self, before: 'QAction') -> 'QAction': ...
    def addSection(self, text: str) -> 'QAction': ...
    def addSection(self, icon: 'QIcon', text: str) -> 'QAction': ...
    def insertSection(self, before: 'QAction', text: str) -> 'QAction': ...
    def insertSection(self, before: 'QAction', icon: 'QIcon', text: str) -> 'QAction': ...
    def removeAction(self, action: 'QAction') -> None: ...
    def clear(self) -> None: ...
    def exec_(self) -> 'QAction': ...
    def exec_(self, pos: QPoint, at: 'QAction' = ...) -> 'QAction': ...
    def popup(self, pos: QPoint, at: 'QAction' = ...) -> None: ...
    def setSeparatorsCollapsible(self, collapse: bool) -> None: ...
    def separatorsCollapsible(self) -> bool: ...
    def setTearOffEnabled(self, enabled: bool) -> None: ...
    def isTearOffEnabled(self) -> bool: ...
    def hideTearOffMenu(self) -> None: ...
    def isTearOffMenuVisible(self) -> bool: ...
    def setIcon(self, icon: 'QIcon') -> None: ...
    def icon(self) -> 'QIcon': ...
    def setTitle(self, title: str) -> None: ...
    def title(self) -> str: ...
    def hovered(self, action: 'QAction') -> Signal: ...
    def triggered(self, action: 'QAction') -> Signal: ...
    def aboutToShow(self) -> Signal: ...
    def aboutToHide(self) -> Signal: ...

class QAction(QObject):
    """动作类"""
    def __init__(self, parent: Optional[QObject] = None) -> None: ...
    def __init__(self, text: str, parent: Optional[QObject] = None) -> None: ...
    def __init__(self, icon: 'QIcon', text: str, parent: Optional[QObject] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setIcon(self, icon: 'QIcon') -> None: ...
    def icon(self) -> 'QIcon': ...
    def setShortcut(self, shortcut: 'QKeySequence') -> None: ...
    def shortcut(self) -> 'QKeySequence': ...
    def setCheckable(self, checkable: bool) -> None: ...
    def isCheckable(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def isChecked(self) -> bool: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def isEnabled(self) -> bool: ...
    def setVisible(self, visible: bool) -> None: ...
    def isVisible(self) -> bool: ...
    def setSeparator(self, b: bool) -> None: ...
    def isSeparator(self) -> bool: ...
    def setToolTip(self, tip: str) -> None: ...
    def toolTip(self) -> str: ...
    def setStatusTip(self, tip: str) -> None: ...
    def statusTip(self) -> str: ...
    def setWhatsThis(self, text: str) -> None: ...
    def whatsThis(self) -> str: ...
    def trigger(self) -> None: ...
    def hover(self) -> None: ...
    def setMenu(self, menu: QMenu) -> None: ...
    def menu(self) -> QMenu: ...
    def triggered(self, checked: bool = ...) -> Signal: ...
    def hovered(self) -> Signal: ...
    def toggled(self, checked: bool) -> Signal: ...
    def changed(self) -> Signal: ...

class QKeySequence:
    """快捷键序列"""
    def __init__(self, key: str) -> None: ...
    def __init__(self, k1: int, k2: int = 0, k3: int = 0, k4: int = 0) -> None: ...
    def toString(self) -> str: ...

class QScreen(QObject):
    """屏幕类"""
    def geometry(self) -> QRect: ...
    def availableGeometry(self) -> QRect: ...
    def size(self) -> QSize: ...
    def availableSize(self) -> QSize: ...
    def logicalDotsPerInch(self) -> float: ...
    def physicalDotsPerInch(self) -> float: ...
    def devicePixelRatio(self) -> float: ...
    def name(self) -> str: ...
    def manufacturer(self) -> str: ...
    def model(self) -> str: ...
    def serialNumber(self) -> str: ...
    def depth(self) -> int: ...
    def refreshRate(self) -> float: ...
    def primaryOrientation(self) -> Qt.ScreenOrientation: ...
    def orientation(self) -> Qt.ScreenOrientation: ...
    def nativeOrientation(self) -> Qt.ScreenOrientation: ...
    def orientationUpdateMask(self) -> Qt.ScreenOrientations: ...
    def setOrientationUpdateMask(self, mask: Qt.ScreenOrientations) -> None: ...
    def grabWindow(self, window: int = 0, x: int = 0, y: int = 0, w: int = -1, h: int = -1) -> 'QPixmap': ...
    def geometryChanged(self, geometry: QRect) -> Signal: ...
    def availableGeometryChanged(self, geometry: QRect) -> Signal: ...
    def physicalSizeChanged(self, size: 'QSizeF') -> Signal: ...
    def physicalDotsPerInchXChanged(self, dpi: float) -> Signal: ...
    def physicalDotsPerInchYChanged(self, dpi: float) -> Signal: ...
    def logicalDotsPerInchXChanged(self, dpi: float) -> Signal: ...
    def logicalDotsPerInchYChanged(self, dpi: float) -> Signal: ...
    def virtualGeometryChanged(self, rect: QRect) -> Signal: ...
    def primaryOrientationChanged(self, orientation: Qt.ScreenOrientation) -> Signal: ...
    def orientationChanged(self, orientation: Qt.ScreenOrientation) -> Signal: ...
    def refreshRateChanged(self, refreshRate: float) -> Signal: ...

class QWindow:
    """窗口类"""
    pass
